[package]
name = "pslbench"
version = "0.1.0"
authors = ["Rushmore Mushambi <rushmore@webenchanter.com>"]
publish = false
edition = "2021"

[dependencies]
psl = "2"
publicsuffix = { version = "2", default-features = false, features = ["hashbrown"] }
