[package]
name = "pslbench"
version = "0.1.0"
authors = ["Jacek Wielemborek <d33tah@gmail.com>"]

[[bin]]
name = "pslbench"
path = "main.rs"

[dependencies.psl]
version = "0.4"

[profile.release]
lto = true
